// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm0qLzR0UrlvXO7CWYiPzIhCpQX3oW5VA',
    appId: '1:1005265932079:web:49c9d2adcfb77bc530dbda',
    messagingSenderId: '1005265932079',
    projectId: 'authsys-bdb6d',
    authDomain: 'authsys-bdb6d.firebaseapp.com',
    storageBucket: 'authsys-bdb6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOH1v2CrPuzK521xpPLP59Ql0jvilV4P8',
    appId: '1:1005265932079:android:5e906adadb99f6cb30dbda',
    messagingSenderId: '1005265932079',
    projectId: 'authsys-bdb6d',
    storageBucket: 'authsys-bdb6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpc9IFb5HJK-C-ejmTjUaZn1N1AxhCyA',
    appId: '1:1005265932079:ios:f44f903d2eb6616e30dbda',
    messagingSenderId: '1005265932079',
    projectId: 'authsys-bdb6d',
    storageBucket: 'authsys-bdb6d.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpc9IFb5HJK-C-ejmTjUaZn1N1AxhCyA',
    appId: '1:1005265932079:ios:6391a95fd3f1e5a330dbda',
    messagingSenderId: '1005265932079',
    projectId: 'authsys-bdb6d',
    storageBucket: 'authsys-bdb6d.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
